spring:
  application:
    name: eureka-server-single

server:
  port: 7001

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #euraka实例列表中显示的id
    hostname: eureka-server-7001.com #eureka服务端的实例名称，DS Replicas栏显示的名称
  client:
    #该应用为注册中心，设置为false表示不向注册中心注册自己，集群配置是必须设置为true
    register-with-eureka: false
    #该应用为注册中心，设置为false表示不需要要去检索服务，集群配置是必须设置为true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server-7001.com:7001/eureka/

logging:
  level:
    root: debug
