spring:
  application:
    name: eureka-server

server:
  port: 1111
eureka:
  instance:
    hostname: eureka-server-node1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #该应用为注册中心，设置为false表示不向注册中心注册自己
    register-with-eureka: true
    #该应用为注册中心，设置为false表示不需要要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-node2:1112/eureka/