server:
  port: 9002

spring:
  application:
    name: zuul-server

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #euraka实例列表中显示的id
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server-7001.com:7001/eureka/,http://eureka-server-7002.com:7002/eureka/,http://eureka-server-7003.com:7003/eureka/

info:
  app.name: ${spring.application.name}
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

zuul:
  routes:
    ignored-services: #忽略某个服务名，如果所有的话写 '*'
      - provider-server
    provider.serviceId: provider-server #完整的服务名称
    provider.path: /provider/** #映射的微服务别名